### R code

The data are the percent change in total personnel for n=10 companies (1.2,1.4,-0.5,0.3,0.9,2.3,1.0,0.1,1.3,1.9). We assume such changes follow a normal distribution with known variance (but mean is unknown). For the mean (i.e., $\mu$), we assume it follows a t distribution (i.e., the prior for the $\mu$ is t-distribution).Since t-distribution prior is not conjugate to a normal distribution, the posterior distribution is not in a standard form that we can easily sample. Thus, we need to set up a Markov chain whose stationary distribution is the posterior distribution.

$$p(\mu|y_1,...,y_n) \propto \frac{exp[n(\bar{y}\mu-\mu^2/2)]}{1+\mu^2}$$


$$log(g(\mu))=n(\bar{y}\mu-\mu^2/2)-log(1+\mu^2)$$


```{R}
lg=function(mu, n, ybar)
{ mu2=mu^2
  n*(ybar*mu-mu2/2)-log(1+mu2)}

mu_now=10
cand_sd=5
y=c(1.2,1.4,-0.5,0.3,0.9,2.3,1.0,0.1,1.3,1.9)
ybar=mean(y)

mh<-function(mu_now,type_MH,cand_sd)
{
m=1000
n=length(y)
mu_storage<-c()
mu_storage<-c(mu_storage,mu_now)
acceptance_count=0

for (i in 1:m)
{
  if (type_MH=="randomwalk")  # random walk
  {
  mu_cand = rnorm(n=1, mean=mu_now, sd=cand_sd)
  }
  else
  {
    if(type_MH=="independent")  # independent, as mean is fixed
    {mu_cand = rnorm(n=1, mean=3, sd=cand_sd)}
    else
    {print("woring type of MH")
     break
    }
  }
  
  lg_alpha=lg(mu_cand,n=n,ybar = ybar)-lg(mu_now,n=n,ybar=ybar)
  alpha=exp(lg_alpha)
  if(alpha>1)
    {mu_now=mu_cand
    mu_storage<-c(mu_storage,mu_cand)
    acceptance_count=acceptance_count+1}
  else
    {random_p=runif(1)
    if(alpha>random_p)
      {mu_now=mu_cand
      acceptance_count=acceptance_count+1}
    else
      {mu_now=mu_now}
    }
}

list(mu=mu_storage,accpt=acceptance_count/m)
}

tt_0<-mh(mu_now=5,type_MH="randomwalk",cand_sd=10)
plot.ts(tt_0$mu)
tt_0$accpt

tt_1<-mh(mu_now=5,type_MH="randomwalk",cand_sd=0.005)
plot.ts(tt_1$mu)
tt_1$accpt

tt_2<-mh(mu_now=5,type_MH="randomwalk",cand_sd=0.5)
plot.ts(tt_2$mu)
tt_2$accpt
```

As we can see, when the variance is big, the acceptance rate is low. When the variance is low, in conrast, the acceptance rate is high. Note that, changing the mean does not change the acceptance rate too much. In the following, I plotted the prior, posteior, and the sample(i.e., $y$).


```{R}
mu_keep<-tt_2$mu[-c(1:2)]
plot(density(mu_keep),xlim=c(-3,6))
curve(dt(x,df=1),lty=2,add = TRUE,col="red")
legend("topright",legend=c("Prior t-distribution pdf", "Posterior pdf"), col=c("red","black"), lty=1, bty="n")
points(ybar,0,pch=20)
legend(1,1, legend="The black dot is the mean of y",bty="n")
```

In the following, I show the situation that the proposal distribution is not random walk, but rather independent. That is, the mean for the normal distribution is fixed. Refer to the procedure of MH, there is a setence of:

<center>

__Draw candidate $\theta^* \sim q(\theta^*|\theta_{i-1})$__

</center>

```{R}
tt_3<-mh(mu_now=5,type_MH="independent",cand_sd=0.5)
plot.ts(tt_3$mu)
tt_3$accpt

#tt_4<-mh(mu_now=5,type_MH="hello",cand_sd=0.5)
#tt_4
```